version: '3.9'

services:

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pedido_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    networks:
      - rabbit-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - rabbit-net

networks:
  rabbit-net:
    driver: bridge
